//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessiaOneZininaMatveeva.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public int GenderId { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string CountryId { get; set; }
        public string Phone { get; set; }
        public int DirectionId { get; set; }
        public int EventId { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Event Event { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
